// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function BuilderPattern(User) {
  var setName = function (builder, name) {
    builder.name = name;
    
  };
  var getName = function (builder) {
    return builder.name;
  };
  var setAge = function (builder, age) {
    builder.age = age;
    
  };
  var getAge = function (builder) {
    return builder.age;
  };
  var setPhone = function (builder, phone) {
    builder.phone = phone;
    
  };
  var getPhone = function (builder) {
    return builder.phone;
  };
  var setAddress = function (builder, address) {
    builder.address = address;
    
  };
  var getAddress = function (builder) {
    return builder.address;
  };
  var getResult = function (builder) {
    return Curry._4(User.create, builder.name, builder.age, builder.phone, builder.address);
  };
  return {
          setName: setName,
          getName: getName,
          setAge: setAge,
          getAge: getAge,
          setPhone: setPhone,
          getPhone: getPhone,
          setAddress: setAddress,
          getAddress: getAddress,
          getResult: getResult
        };
}

function Director(User, Builder) {
  var construct = function (builder) {
    Curry._2(Builder.setName, builder, "Charles");
    Curry._2(Builder.setAge, builder, 120);
    Curry._2(Builder.setPhone, builder, "(123) 456-7890");
    Curry._2(Builder.setAddress, builder, "123 Fake St.");
    console.log(Curry._1(Builder.getName, builder));
    console.log(Curry._1(Builder.getAge, builder));
    console.log(Curry._1(Builder.getPhone, builder));
    console.log(Curry._1(Builder.getAddress, builder));
    
  };
  return {
          construct: construct
        };
}

function create(name, age, phone, address) {
  return {
          name: name,
          age: age,
          phone: phone,
          address: address
        };
}

var ConcreteUser = {
  name: "Charles",
  age: 120,
  phone: "(123) 456-7890",
  address: "123 Fake St.",
  create: create
};

function setName(builder, name) {
  builder.name = name;
  
}

function getName(builder) {
  return builder.name;
}

function setAge(builder, age) {
  builder.age = age;
  
}

function getAge(builder) {
  return builder.age;
}

function setPhone(builder, phone) {
  builder.phone = phone;
  
}

function getPhone(builder) {
  return builder.phone;
}

function setAddress(builder, address) {
  builder.address = address;
  
}

function getAddress(builder) {
  return builder.address;
}

function getResult(builder) {
  return create(builder.name, builder.age, builder.phone, builder.address);
}

var MyBuilder = {
  setName: setName,
  getName: getName,
  setAge: setAge,
  getAge: getAge,
  setPhone: setPhone,
  getPhone: getPhone,
  setAddress: setAddress,
  getAddress: getAddress,
  getResult: getResult
};

function construct(builder) {
  setName(builder, "Charles");
  setAge(builder, 120);
  setPhone(builder, "(123) 456-7890");
  setAddress(builder, "123 Fake St.");
  console.log(getName(builder));
  console.log(getAge(builder));
  console.log(getPhone(builder));
  console.log(getAddress(builder));
  
}

var DisplayName = {
  construct: construct
};

Curry._1(DisplayName.construct, {
      name: "Henry",
      age: 200,
      phone: "words words",
      address: "address address"
    });

exports.BuilderPattern = BuilderPattern;
exports.Director = Director;
exports.ConcreteUser = ConcreteUser;
exports.MyBuilder = MyBuilder;
exports.DisplayName = DisplayName;
/*  Not a pure module */
