// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var shared = ["windowWidth"];

function screenSize_001($$class) {
  CamlinternalOO.get_method_label($$class, "windowWidth");
  return (function (env, self) {
      return CamlinternalOO.create_object_opt(self, $$class);
    });
}

var screenSize = /* class */[
  undefined,
  screenSize_001,
  undefined,
  undefined
];

function macWindowSize_init($$class) {
  var width = CamlinternalOO.new_variable($$class, "");
  var windowWidth = CamlinternalOO.get_method_label($$class, "windowWidth");
  var inh = CamlinternalOO.inherits($$class, 0, shared, 0, screenSize, true);
  var obj_init = inh[0];
  CamlinternalOO.set_method($$class, windowWidth, (function (self$2, param) {
          return self$2[width];
        }));
  return (function (env, self, width$1) {
      var self$1 = CamlinternalOO.create_object_opt(self, $$class);
      self$1[width] = width$1;
      Curry._1(obj_init, self$1);
      return CamlinternalOO.run_initializers_opt(self, self$1, $$class);
    });
}

var macWindowSize = CamlinternalOO.make_class(shared, macWindowSize_init);

exports.screenSize = screenSize;
exports.macWindowSize = macWindowSize;
/* macWindowSize Not a pure module */
