// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Singleton$ReasonOopPatterns = require("./singleton.bs.js");
var SingletonCopy$ReasonOopPatterns = require("./singletonCopy.bs.js");

console.log(Singleton$ReasonOopPatterns.fivePlusFive);

console.log(SingletonCopy$ReasonOopPatterns.fivePlusFive);

var exampleOne = Singleton$ReasonOopPatterns.fivePlusFive;

var exampleTwo = SingletonCopy$ReasonOopPatterns.fivePlusFive;

exports.exampleOne = exampleOne;
exports.exampleTwo = exampleTwo;
/*  Not a pure module */
