// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_oo_curry = require("bs-platform/lib/js/caml_oo_curry.js");
var AbstractFactory$ReasonOopPatterns = require("./abstractFactory.bs.js");

function show(param) {
  var factory1 = Curry._1(AbstractFactory$ReasonOopPatterns.concreteFactory1[0], undefined);
  var tester1 = Curry._2(AbstractFactory$ReasonOopPatterns.testFactory[0], undefined, factory1);
  Caml_oo_curry.js2(-856045486, 1, tester1, undefined);
  var factory2 = Curry._1(AbstractFactory$ReasonOopPatterns.concreteFactory2[0], undefined);
  var tester2 = Curry._2(AbstractFactory$ReasonOopPatterns.testFactory[0], undefined, factory2);
  return Caml_oo_curry.js2(-856045486, 2, tester2, undefined);
}

show(undefined);

exports.show = show;
/*  Not a pure module */
